service: nm-parser

package:
  exclude:
    - node_modules/**

custom:
  bucket: usman-test-bucket-333
  bucketPath: styles/messages
  queueName: nmQueue
  queueUrl: https://sqs.${self:provider.region}.amazonaws.com


provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  environment:
    BUCKET: ${self:custom.bucket}
    BUCKET_PATH: ${self:custom.bucketPath}
    QUEUE_NAME: ${self:custom.queueName}
    QUEUE_URL: ${self:custom.queueUrl}

  iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:PutObject
          - s3:GetObject
        Resource: "arn:aws:s3:::${self:custom.bucket}/*"
      - Effect: "Allow"
        Action:
          - "sqs:SendMessage"
          - "sqs:GetQueueUrl"
        Resource:
          - 'Fn::Join':
            - ':'
            -
              - 'arn:aws:sqs'
              - Ref: 'AWS::Region'
              - Ref: 'AWS::AccountId'
              - '${self:custom.queueName}'
      - Effect: "Allow"
        Action:
          - "sqs:ListQueues"
        Resource:
          - 'Fn::Join':
            - ':'
            -
              - 'arn:aws:sqs'
              - '${self:provider.region}'
              - Ref: 'AWS::AccountId'
              - '*'


functions:
#  saveXml:
#    handler: saveXml.handler
#    environment:
#        BUCKET: ${self:custom.bucket}
#    events:
#      - http:
#          path: save/xml
#          method: post

  saveJson:
    handler: saveJson.handler
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .xml

  sender:
      handler: sender.handler
      environment:
        QUEUE_URL: https://sqs.${self:provider.region}.amazonaws.com
        QUEUE_NAME: ${self:custom.queueName}
      events:
        - http:
            path: v1/sender
            method: post

  receiver:
    handler: receiver.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ${self:custom.queueName}
              - Arn

resources:
  Resources:
    nmQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:custom.queueName}